Friendly_id Implemented
wx-inc-trainings/np-rails pull request #13
Opened 2021-06-11 11:10 UTC by nicoopalenque

# Sumary

* Implement Friendly id in the route Show
* Use the title field instead of the book id

# Card

[https://trello.com/c/64ksmU9l](url)

# Screenshot

![Captura de Pantalla 2021-06-11 a la(s) 07 58 43](https://user-images.githubusercontent.com/52846611/121677485-50841e00-ca8c-11eb-99a2-c7a922bddffd.png)

2021-06-11 14:25 UTC, blacksam07 requested changes

2021-06-11 14:25 UTC, blacksam07 commented on app/models/book.rb
> +  extend FriendlyId
move to top of class 

read this https://github.com/rubocop/ruby-style-guide#consistent-classes

2021-06-14 13:36 UTC, redwarewolf approved these changes

2021-06-14 13:37 UTC, redwarewolf approved these changes

2021-06-15 13:32 UTC, blacksam07 approved these changes

2021-06-15 18:18 UTC, merged