Test book
wx-inc-trainings/np-rails pull request #14
Opened 2021-06-14 18:17 UTC by nicoopalenque

# Sumary

* Create tests for Index and Show routes from Book

# Card

[https://trello.com/c/QG6iF4CF](url)

# Screenshot

![Captura de Pantalla 2021-06-14 a la(s) 15 08 25](https://user-images.githubusercontent.com/52846611/121939584-8c84e080-cd23-11eb-8e4d-fcaf099c40ff.png)

2021-06-15 14:07 UTC, blacksam07 requested changes

2021-06-15 14:07 UTC, blacksam07 commented on spec/controller/book_controller_spec.rb
> +  describe 'GET #index' do
use fuctium

2021-06-15 14:07 UTC, blacksam07 commented on spec/controller/book_controller_spec.rb
> +        resp = JSON.parse(response.body)
you can use be_paginated of wor-paginate https://github.com/Wolox/wor-paginate#test-helpers

2021-06-15 14:07 UTC, blacksam07 commented on spec/factories/user.rb
> +    email { 'test@wolox.com.ar' }
Use Faker

2021-06-15 19:37 UTC, blacksam07 commented on spec/controller/book_controller_spec.rb
> +      end
you can define this inside spec/support/parsed_response_body.rb

```ruby
module Response
  module JSONParser
    def response_body
      ActiveSupport::JSON.decode(response.body) if response.present? && response.body.present?
    end
  end
end
```

2021-06-16 13:04 UTC, blacksam07 approved these changes

2021-06-16 17:29 UTC, redwarewolf requested changes

2021-06-16 17:29 UTC, redwarewolf commented on spec/controller/book_controller_spec.rb
> +RSpec.describe Api::V1::BookController, type: :controller do
You are missing the tests for failure scenarios

2021-06-23 02:41 UTC, merged